version: '2'
services:
  mysql:
    # image: mysql:5.7.21
    image: mysql:8.0.26
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    hostname: 'mysql'
    environment:
      MYSQL_DATABASE: 'slidehub'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: 'Dockerfile'
      args:
        INSTALL_MAILCATCHER: "true" # 開発環境用
        SUPERVISOR_CONF: "script/oss_docker_supervisor_dev.conf"
        EXPOSE_PORTS: "3000 1080"
    depends_on:
      - mysql
    environment:
      RAILS_ENV: development
      OSS_USE_AZURE: 1
      OSS_AZURE_CONTAINER_NAME: $OSS_AZURE_CONTAINER_NAME
      OSS_AZURE_IMAGE_CONTAINER_NAME: $OSS_AZURE_IMAGE_CONTAINER_NAME
      OSS_AZURE_CDN_BASE_URL: $OSS_AZURE_CDN_BASE_URL
      OSS_AZURE_QUEUE_NAME: $OSS_AZURE_QUEUE_NAME
      OSS_AZURE_STORAGE_ACCOUNT_NAME: $OSS_AZURE_STORAGE_ACCOUNT_NAME
      OSS_AZURE_STORAGE_ACCESS_KEY: $OSS_AZURE_STORAGE_ACCESS_KEY
      OSS_DB_NAME_DEV: 'slidehub'
      OSS_DB_USERNAME_DEV: 'root'
      OSS_DB_PASSWORD_DEV: 'pass'
      OSS_DB_URL_DEV: 'mysql'
      OSS_DB_NAME_TEST: 'test_slidehub'
      OSS_DB_USERNAME_TEST: 'root'
      OSS_DB_PASSWORD_TEST: 'pass'
      OSS_DB_URL_TEST: 'mysql'
      OSS_FACEBOOK_APP_ID: $OSS_FACEBOOK_APP_ID
      OSS_FACEBOOK_APP_SECRET: $OSS_FACEBOOK_APP_SECRET
      OSS_TWITTER_CONSUMER_KEY: $OSS_TWITTER_CONSUMER_KEY
      OSS_TWITTER_CONSUMER_SECRET: $OSS_TWITTER_CONSUMER_SECRET
      OSS_TWITTER_CALLBACK_URL: 'http://localhost:3000/users/auth/twitter/callback'
      OSS_IDP_CERT_FINGERPRINT: $OSS_IDP_CERT_FINGERPRINT
      OSS_IDP_SSO_TERGET_URL: $OSS_IDP_SSO_TARGET_URL
      OSS_FROM_EMAIL: test@example.com
      OSS_SMTP_SERVER: localhost
      OSS_SMTP_PORT: 1025
      OSS_SMTP_AUTH_METHOD: plain
      OSS_SMTP_PASSWORD: test
      OSS_SMTP_USERNAME: test
      OSS_ROOT_URL: http://localhost:3000
      OSS_LOGIN_REQUIRED: $OSS_LOGIN_REQUIRED
      RAILS_LOG_TO_STDOUT: 'yes'
      OSS_TIMEZONE: 'Asia/Tokyo'
    ports:
      - '3000:3000'
      - '1080:1080'
    volumes:
      - .:/opt/application/current:cached

volumes:
  mysql-data:
    driver: local
