<% require_relative '../lib/slide_hub/env_util' %>
amazon:
  service: S3
  access_key_id: <%= SlideHub::EnvUtil.fetch('AWS_ACCESS_ID', '') %>
  secret_access_key: <%= SlideHub::EnvUtil.fetch('AWS_SECRET_KEY', '') %>
  region: <%= SlideHub::EnvUtil.fetch('REGION', '') %>
  bucket: <%= SlideHub::EnvUtil.fetch('IMAGE_BUCKET_NAME', '') %>

azure:
  service: AzureStorage
  storage_account_name: <%= SlideHub::EnvUtil.fetch('AZURE_STORAGE_ACCOUNT_NAME', '') %>
  storage_access_key: <%= SlideHub::EnvUtil.fetch('AZURE_STORAGE_ACCESS_KEY', '') %>
  container: <%= SlideHub::EnvUtil.fetch('AZURE_IMAGE_CONTAINER_NAME', '') %>
