# -*- coding: utf-8 -*-
task :default => :build

task :build do
  cmd = 'docker build -t ryuzee/slidehub-base .'
  sh cmd
end

task :push do
  cmd = 'docker push ryuzee/slidehub-base:latest'
  sh cmd
end

